import { afterEach, describe, expect, it } from 'bun:test';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { SCHEMAS } from './decorators.ts';
import {
  generateOpenAPI,
  generateOpenAPIDocument,
  type OpenAPIDocument,
  type OpenAPIOperation,
  OpenAPIOperationError,
  writeOpenAPIDocument,
} from './openapi.ts';

const temporaryDirectories: string[] = [];

afterEach(() => {
  for (const directory of temporaryDirectories.splice(0)) {
    rmSync(directory, { recursive: true, force: true });
  }
});

function temporaryDirectory(): string {
  const directory = mkdtempSync(join(tmpdir(), 'di-framework-openapi-'));
  temporaryDirectories.push(directory);
  return directory;
}

function operationAt(document: OpenAPIDocument, path: string, method: string): OpenAPIOperation {
  const operation = document.paths[path]?.[method];
  if (!operation) throw new Error(`Missing OpenAPI operation ${method.toUpperCase()} ${path}`);
  return operation;
}

describe('generateOpenAPI', () => {
  it('should generate a default OpenAPI spec with default options', () => {
    const spec = generateOpenAPI({}, { getTargets: () => new Set() });

    expect(spec.openapi).toBe('3.1.0');
    expect(spec.info.title).toBe('Generated API');
    expect(spec.info.version).toBe('1.0.0');
    expect(spec.info.description).toBe('API documentation generated by @di-framework/http.');
    expect(spec.paths).toEqual({});
    expect(spec.components.schemas).toEqual({});
  });

  it('should use provided options in the OpenAPI spec', () => {
    const options = {
      title: 'Custom API',
      version: '2.0.0',
      description: 'Custom description',
    };
    const spec = generateOpenAPI(options, {
      getTargets: () => new Set(),
    });

    expect(spec.info.title).toBe('Custom API');
    expect(spec.info.version).toBe('2.0.0');
    expect(spec.info.description).toBe('Custom description');
  });

  it('should correctly map a registry with controllers and endpoints', () => {
    // Mocking the structure that decorators create
    const mockController = class TestController {};
    // @ts-expect-error
    mockController.post = () => {};
    // @ts-expect-error
    mockController.post.isEndpoint = true;
    // @ts-expect-error
    mockController.post.path = '/test';
    // @ts-expect-error
    mockController.post.method = 'post';
    // @ts-expect-error
    mockController.post.metadata = {
      summary: 'Test Summary',
      description: 'Test Description',
      requestBody: { content: { 'application/json': {} } },
      responses: { '201': { description: 'Created' } },
    };

    const registry = { getTargets: () => new Set([mockController]) };
    const spec = generateOpenAPI({}, registry);

    expect(spec.paths['/test']).toBeDefined();
    const operation = operationAt(spec, '/test', 'post');
    expect(operation.summary).toBe('Test Summary');
    expect(operation.description).toBe('Test Description');
    expect(operation.operationId).toBe('TestController.post');
    expect(operation.requestBody).toBeDefined();
    expect(operation.responses['201']).toBeDefined();
  });

  it('should handle endpoints without metadata', () => {
    const mockController = class SimpleController {};
    // @ts-expect-error
    mockController.get = () => {};
    // @ts-expect-error
    mockController.get.isEndpoint = true;
    // @ts-expect-error
    mockController.get.path = '/simple';
    // @ts-expect-error
    mockController.get.method = 'get';

    const registry = { getTargets: () => new Set([mockController]) };
    const spec = generateOpenAPI({}, registry);

    const operation = operationAt(spec, '/simple', 'get');
    expect(operation.summary).toBe('get'); // defaults to property key
    expect(operation.responses['200']).toBeDefined(); // default response
    expect(operation.responses['200']?.description).toBe('OK');
  });

  it('should handle multiple endpoints on the same path', () => {
    const mockController = class MultiController {};
    // @ts-expect-error
    mockController.get = () => {};
    // @ts-expect-error
    mockController.get.isEndpoint = true;
    // @ts-expect-error
    mockController.get.path = '/resource';
    // @ts-expect-error
    mockController.get.method = 'get';

    // @ts-expect-error
    mockController.post = () => {};
    // @ts-expect-error
    mockController.post.isEndpoint = true;
    // @ts-expect-error
    mockController.post.path = '/resource';
    // @ts-expect-error
    mockController.post.method = 'post';

    const registry = { getTargets: () => new Set([mockController]) };
    const spec = generateOpenAPI({}, registry);

    expect(spec.paths['/resource']?.get).toBeDefined();
    expect(spec.paths['/resource']?.post).toBeDefined();
  });

  it('should handle unknown path and method defaults', () => {
    const mockController = class WeirdController {};
    // @ts-expect-error
    mockController.weird = () => {};
    // @ts-expect-error
    mockController.weird.isEndpoint = true;
    // Note: missing path and method

    const registry = { getTargets: () => new Set([mockController]) };
    const spec = generateOpenAPI({}, registry);

    expect(spec.paths['/unknown']).toBeDefined();
    expect(spec.paths['/unknown']?.get).toBeDefined();
  });

  it('should convert :param paths to {param} and inject path parameters', () => {
    const mockController = class ParamController {};
    // @ts-expect-error
    mockController.getUser = () => {};
    // @ts-expect-error
    mockController.getUser.isEndpoint = true;
    // @ts-expect-error
    mockController.getUser.path = '/users/:userId/posts/:postId';
    // @ts-expect-error
    mockController.getUser.method = 'get';

    const registry = { getTargets: () => new Set([mockController]) };
    const spec = generateOpenAPI({}, registry);

    const openApiPath = '/users/{userId}/posts/{postId}';
    expect(spec.paths[openApiPath]).toBeDefined();
    const operation = operationAt(spec, openApiPath, 'get');
    const parameters = operation.parameters ?? [];
    expect(parameters).toHaveLength(2);
    expect(parameters[0]).toEqual({
      name: 'userId',
      in: 'path',
      required: true,
      schema: { type: 'string' },
    });
    expect(parameters[1]?.name).toBe('postId');
  });

  it('should combine automatic path parameters with decorator parameters', () => {
    const mockController = class MixController {};
    // @ts-expect-error
    mockController.get = () => {};
    // @ts-expect-error
    mockController.get.isEndpoint = true;
    // @ts-expect-error
    mockController.get.path = '/items/:id';
    // @ts-expect-error
    mockController.get.method = 'get';
    // @ts-expect-error
    mockController.get.metadata = {
      parameters: [{ name: 'filter', in: 'query' }],
    };

    const registry = { getTargets: () => new Set([mockController]) };
    const spec = generateOpenAPI({}, registry);

    const operation = operationAt(spec, '/items/{id}', 'get');
    const parameters = operation.parameters ?? [];
    expect(parameters).toHaveLength(2);
    expect(parameters[0]?.name).toBe('id');
    expect(parameters[0]?.in).toBe('path');
    expect(parameters[1]?.name).toBe('filter');
    expect(parameters[1]?.in).toBe('query');
  });

  it('should resolve referenced component schemas via the SCHEMAS symbol', () => {
    const mockController = class SchemaController {};
    // @ts-expect-error
    mockController[SCHEMAS] = new Set(['User', 'Post']);

    const registry = { getTargets: () => new Set([mockController]) };

    // Provide the schema definitions in options
    const schemas = {
      User: {
        type: 'object',
        properties: { id: { type: 'string' }, profile: { $ref: '#/components/schemas/Profile' } },
      },
      Post: {
        type: 'object',
        properties: {
          comments: [{ $ref: '#/components/schemas/Comment' }],
        },
      },
      Comment: { type: 'object', properties: { text: { type: 'string' } } },
      Profile: { type: 'object', properties: { age: { type: 'integer' } } }, // Transitive ref
      Unused: { type: 'object' }, // Should not be included
    };

    const spec = generateOpenAPI({ schemas }, registry);

    const resolved = spec.components.schemas;
    expect(resolved.User).toBeDefined();
    expect(resolved.Post).toBeDefined();
    expect(resolved.Profile).toBeDefined(); // Transitively resolved!
    expect(resolved.Comment).toBeDefined(); // Transitively resolved from array!
    expect(resolved.Unused).toBeUndefined();
  });
});

describe('programmatic OpenAPI operations', () => {
  it('loads explicit controller modules and returns a typed document result', async () => {
    const cwd = temporaryDirectory();
    const loaded: string[] = [];
    const result = await generateOpenAPIDocument({
      controllerModules: ['./controllers.ts'],
      cwd,
      configuration: { title: 'Programmatic API', version: '2.1.0' },
      registry: { getTargets: () => new Set() },
      importModule: async (modulePath) => {
        loaded.push(modulePath);
        return {};
      },
    });

    expect(loaded).toEqual([join(cwd, 'controllers.ts')]);
    expect(result.controllerModules).toEqual(loaded);
    expect(result.document.info).toEqual({
      title: 'Programmatic API',
      version: '2.1.0',
      description: 'API documentation generated by @di-framework/http.',
    });
  });

  it('returns typed failures for missing and unloadable controller inputs', async () => {
    await expect(generateOpenAPIDocument({ controllerModules: [] })).rejects.toMatchObject({
      name: 'OpenAPIOperationError',
      code: 'controllers-required',
    });

    const cwd = temporaryDirectory();
    const cause = new Error('module exploded');
    try {
      await generateOpenAPIDocument({
        controllerModules: ['broken.ts'],
        cwd,
        importModule: async () => {
          throw cause;
        },
      });
      throw new Error('expected controller loading to fail');
    } catch (error) {
      expect(error).toBeInstanceOf(OpenAPIOperationError);
      expect(error).toMatchObject({
        code: 'controller-load-failed',
        path: join(cwd, 'broken.ts'),
        cause,
      });
    }
  });

  it('writes formatted JSON explicitly and reports write failures', () => {
    const cwd = temporaryDirectory();
    const document = generateOpenAPI({}, { getTargets: () => new Set() });
    const result = writeOpenAPIDocument(document, 'openapi.json', cwd);

    expect(result.outputPath).toBe(join(cwd, 'openapi.json'));
    expect(result.bytes).toBeGreaterThan(0);
    expect(JSON.parse(readFileSync(result.outputPath, 'utf8'))).toEqual(document);

    expect(() => writeOpenAPIDocument(document, cwd)).toThrow(
      expect.objectContaining({
        name: 'OpenAPIOperationError',
        code: 'document-write-failed',
        path: cwd,
      }),
    );
  });
});
