import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import type { OwnershipLedger } from './types.ts';

export const OWNERSHIP_HEADER = '// @generated by @di-framework/codegen — do not edit.';

export function hasOwnershipHeader(content: string): boolean {
  return content.trimStart().startsWith(OWNERSHIP_HEADER);
}

export function loadLedger(ledgerPath: string): OwnershipLedger {
  if (!existsSync(ledgerPath)) {
    return { version: '1', generatedFiles: [] };
  }
  try {
    const raw = readFileSync(ledgerPath, 'utf-8');
    const parsed = JSON.parse(raw);
    if (parsed && typeof parsed === 'object' && Array.isArray(parsed.generatedFiles)) {
      return {
        version: String(parsed.version ?? '1'),
        generatedFiles: parsed.generatedFiles.map(String),
      };
    }
  } catch {
    // Ignore invalid JSON ledger
  }
  return { version: '1', generatedFiles: [] };
}

export function saveLedger(ledgerPath: string, generatedFiles: string[]): void {
  const ledgerDir = dirname(ledgerPath);
  if (!existsSync(ledgerDir)) {
    mkdirSync(ledgerDir, { recursive: true });
  }

  const sortedFiles = Array.from(new Set(generatedFiles)).sort();
  const ledger: OwnershipLedger = {
    version: '1',
    generatedFiles: sortedFiles,
  };

  writeFileSync(ledgerPath, JSON.stringify(ledger, null, 2) + '\n', 'utf-8');
}
