import { existsSync, mkdirSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs';
import { dirname, isAbsolute, relative, resolve } from 'node:path';
import type { GeneratedFileResult, OwnershipLedger } from './types.ts';

export const OWNERSHIP_HEADER = '// @generated by @di-framework/codegen — do not edit.';

export function hasOwnershipHeader(content: string): boolean {
  return content.trimStart().startsWith(OWNERSHIP_HEADER);
}

export function loadLedger(ledgerPath: string): OwnershipLedger {
  if (!existsSync(ledgerPath)) {
    return { version: '1', generatedFiles: [] };
  }
  try {
    const raw = readFileSync(ledgerPath, 'utf-8');
    const parsed = JSON.parse(raw);
    if (parsed && Array.isArray(parsed.generatedFiles)) {
      return {
        version: parsed.version ?? '1',
        generatedFiles: parsed.generatedFiles.map(String),
      };
    }
  } catch {
    // Ignore invalid JSON ledger
  }
  return { version: '1', generatedFiles: [] };
}

export function saveLedger(ledgerPath: string, generatedFiles: string[]): void {
  const ledgerDir = dirname(ledgerPath);
  if (!existsSync(ledgerDir)) {
    mkdirSync(ledgerDir, { recursive: true });
  }

  const sortedFiles = Array.from(new Set(generatedFiles)).sort();
  const ledger: OwnershipLedger = {
    version: '1',
    generatedFiles: sortedFiles,
  };

  writeFileSync(ledgerPath, JSON.stringify(ledger, null, 2) + '\n', 'utf-8');
}

export function performSafeCleanup(
  ledgerPath: string,
  newGeneratedFiles: string[],
  cwd: string = process.cwd(),
): GeneratedFileResult[] {
  const oldLedger = loadLedger(ledgerPath);
  const newSet = new Set(newGeneratedFiles.map((f) => resolve(f)));
  const results: GeneratedFileResult[] = [];

  for (const fileInLedger of oldLedger.generatedFiles) {
    const absPath = isAbsolute(fileInLedger) ? fileInLedger : resolve(cwd, fileInLedger);
    if (!newSet.has(absPath)) {
      // It's a stale file recorded in ledger
      if (existsSync(absPath)) {
        const content = readFileSync(absPath, 'utf-8');
        if (hasOwnershipHeader(content)) {
          unlinkSync(absPath);
          results.push({
            path: absPath,
            relativePath: relative(cwd, absPath).replace(/\\/g, '/'),
            content: '',
            status: 'deleted',
          });
        }
      }
    }
  }

  return results;
}
