/**
 * `@di-framework/ai-utils` — agentic extras for `@di-framework/ai`.
 *
 * Agent Skills (SKILL.md / progressive disclosure) live here so the core AI
 * package stays model/tools/RAG/MCP focused, matching Spring's split of
 * spring-ai vs spring-ai-agent-utils.
 */

export type {
  AllowedDirectories,
  PathAccessDenied,
  PathAccessOk,
  PathAccessResult,
} from './sandbox/index.ts';
export {
  assertPathAllowed,
  expandUserPath,
  resolveAllowedDirectories,
  uniqueResolvedRoots,
} from './sandbox/index.ts';
export type {
  AgentSkill,
  AgentSkillCreateOptions,
  CreateSkillsAgentOptions,
  ParseSkillMarkdownOptions,
  SkillsAgentBundle,
  SkillsInput,
  SkillsRuntime,
  SkillsRuntimeOptions,
  SkillsToolboxMemoriesOptions,
  SkillsToolboxOptions,
  SkillsToolboxTaskOptions,
  SkillsToolboxWebOptions,
  SkillsToolOptions,
  ValidateSkillOptions,
} from './skills/index.ts';
export {
  agentSkill,
  collectSkills,
  createSkillsAgent,
  createSkillsAgentBundle,
  createSkillsRuntime,
  createSkillsToolbox,
  DEFAULT_SKILL_DIRECTORY_CANDIDATES,
  DEFAULT_SKILL_TOOL_NAME,
  existingSkillDirectories,
  formatSkillLoadResult,
  formatSkillNotFound,
  loadSkillFile,
  loadSkillsDirectories,
  loadSkillsDirectory,
  parseAllowedTools,
  parseSkillMarkdown,
  resolveSkillPackageDirectories,
  SkillsAgent,
  SkillsAgentBuilder,
  SkillsFluent,
  SkillsTool,
  SkillsToolBuilder,
  SkillsToolbox,
  SkillsToolboxBuilder,
  skillsTool,
  skillsToolbox,
  skillsToolboxAsMcp,
  skillToXml,
  validateSkill,
  validateSkillDescription,
  validateSkillName,
} from './skills/index.ts';
export type {
  AskUserOption,
  AskUserQuestion,
  AskUserQuestionInput,
  AskUserQuestionToolOptions,
  BashConfirmInput,
  BashInput,
  BashToolOptions,
  EditInput,
  EditToolOptions,
  GlobInput,
  GlobToolOptions,
  GrepInput,
  GrepOutputMode,
  GrepToolOptions,
  ListDirectoryInput,
  ListDirectoryToolOptions,
  MemoryToolsOptions,
  QuestionHandler,
  ReadInput,
  ReadToolOptions,
  TaskInput,
  TaskToolOptions,
  TodoItem,
  TodoStatus,
  TodoWriteInput,
  TodoWriteToolOptions,
  WebFetchInput,
  WebFetchToolOptions,
  WebSearchInput,
  WebSearchToolOptions,
  WriteInput,
  WriteToolOptions,
} from './tools/index.ts';
export {
  askUserQuestionTool,
  bashTool,
  compileGlob,
  DEFAULT_BASH_TIMEOUT_MS,
  DEFAULT_MAX_LINE_CHARS,
  DEFAULT_READ_LIMIT,
  editTool,
  formatMemorySystemPrompt,
  gateToolCallback,
  globTool,
  grepTool,
  listDirectoryTool,
  MAX_BASH_TIMEOUT_MS,
  MEMORY_SYSTEM_PROMPT,
  memoryTools,
  readTool,
  taskTool,
  todoWriteTool,
  webFetchTool,
  webSearchTool,
  writeTool,
} from './tools/index.ts';
export type { YamlMap, YamlValue } from './yaml/index.ts';
export { flattenYamlMap, parseYaml, parseYamlMap, yamlValueToString } from './yaml/index.ts';
