/**
 * Discovery and registration codegen for decorated actor classes.
 */
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { relative, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { getActorMetadata } from '../decorators/keys';
import type { Constructor } from '../types';

export interface ActorDiscoveryOptions {
  cwd?: string;
  rootDir?: string;
  patterns?: string[];
  exclude?: string[];
}

export interface DiscoveredActor {
  name: string;
  namespace?: string;
  ctor: Constructor;
  filePath: string;
  exportName: string;
  methods: string[];
  migrationsCount: number;
}

export interface GenerateRegistrationOptions {
  outFilePath?: string;
  importRuntimePath?: string;
}

function findSourceFiles(dir: string, excludeDirs: Set<string>, results: string[]): void {
  if (!existsSync(dir)) return;
  const entries = readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    if (entry.name.startsWith('.') || excludeDirs.has(entry.name)) continue;
    const fullPath = resolve(dir, entry.name);

    if (entry.isDirectory()) {
      findSourceFiles(fullPath, excludeDirs, results);
    } else if (
      entry.isFile() &&
      (entry.name.endsWith('.ts') || entry.name.endsWith('.js')) &&
      !entry.name.endsWith('.d.ts') &&
      !entry.name.endsWith('.test.ts') &&
      !entry.name.endsWith('.spec.ts')
    ) {
      results.push(fullPath);
    }
  }
}

/**
 * Discovers decorated actor classes in the given directory or project.
 */
export async function discoverActorClasses(
  options: ActorDiscoveryOptions = {},
): Promise<DiscoveredActor[]> {
  const cwd = options.cwd ?? process.cwd();
  const rootDir = options.rootDir ? resolve(cwd, options.rootDir) : cwd;
  const excludeDirs = new Set([
    'node_modules',
    'dist',
    '.git',
    'build',
    ...(options.exclude ?? []),
  ]);

  const candidateFiles: string[] = [];
  findSourceFiles(rootDir, excludeDirs, candidateFiles);

  const discovered: DiscoveredActor[] = [];

  for (const filePath of candidateFiles) {
    let fileContent: string;
    try {
      fileContent = readFileSync(filePath, 'utf8');
    } catch {
      continue;
    }

    // Fast check if file references @Actor or di-framework actors
    const referencesActors = ['@Actor', 'di-framework-actors', '@di-framework/actors'].some(
      (marker) => fileContent.includes(marker),
    );
    if (!referencesActors) continue;

    let mod: any;
    try {
      mod = await import(pathToFileURL(filePath).href);
    } catch (err) {
      // Skip files that fail dynamic import
      continue;
    }

    for (const [exportName, exported] of Object.entries(mod)) {
      if (typeof exported === 'function' && exported.prototype) {
        const meta = getActorMetadata(exported);
        if (meta) {
          discovered.push({
            name: meta.name || exported.name,
            namespace: meta.namespace,
            ctor: exported as Constructor,
            filePath,
            exportName,
            methods: Array.from(meta.methods.keys()).map(String),
            migrationsCount: meta.migrations?.length ?? 0,
          });
        }
      }
    }
  }

  return discovered;
}

/**
 * Generates TypeScript registration code for discovered actors.
 */
export function generateActorRegistration(
  actors: DiscoveredActor[],
  options: GenerateRegistrationOptions = {},
): string {
  const lines: string[] = [
    '/**',
    ' * Auto-generated by @di-framework/actors.',
    ' * Discovered actor registrations for local development and build.',
    ' */',
    `import type { ActorRuntime } from ${JSON.stringify(options.importRuntimePath ?? '@di-framework/actors')};`,
  ];

  if (actors.length === 0) {
    lines.push(
      '',
      'export function registerDiscoveredActors(runtime: ActorRuntime): void {',
      '  // No decorated actors discovered',
      '}',
      '',
    );
    return lines.join('\n');
  }

  const outDir = options.outFilePath ? resolve(options.outFilePath, '..') : process.cwd();
  for (const [index, actor] of actors.entries()) {
    let rel = relative(outDir, actor.filePath).replace(/\\/g, '/');
    if (!rel.startsWith('.')) rel = './' + rel;
    if (rel.endsWith('.ts')) rel = rel.slice(0, -3) + '.js';
    lines.push(
      `import { ${actor.exportName} as DiscoveredActor${index} } from ${JSON.stringify(rel)};`,
    );
  }
  lines.push('', 'export function registerDiscoveredActors(runtime: ActorRuntime): void {');
  for (const [index, actor] of actors.entries()) {
    lines.push(
      `  runtime.register(DiscoveredActor${index}, ${JSON.stringify({ name: actor.name, namespace: actor.namespace })});`,
    );
  }

  lines.push('}', '');
  return lines.join('\n');
}
