import { describe, expect, it } from 'bun:test';
import { emitEventsSurface } from '../src/emitters/events.ts';
import { emitHttpSurface } from '../src/emitters/http.ts';
import { emitRpcSurface } from '../src/emitters/rpc.ts';
import { emitToolsSurface } from '../src/emitters/tools.ts';
import { emitValidationSurface } from '../src/emitters/validation.ts';
import type { NormalizedManifest } from '../src/types.ts';

describe('Surface Emitters', () => {
  const dummySchema = {
    parse: (val: unknown) => val,
    jsonSchema: { type: 'object' },
  };

  const sampleNormManifest: NormalizedManifest = {
    name: 'orders',
    version: 'v1',
    manifestFilePath: '/app/src/contracts/orders-v1.codegen.ts',
    outputDir: '/app/src/generated/orders/v1',
    httpPrefix: '/v1',
    managedByDi: true,
    schemas: {
      CreateOrder: {
        name: 'CreateOrder',
        runtimeSchema: dummySchema,
        modulePath: '/app/src/contracts/orders.schemas.ts',
        relativeModulePathFromGen: '../../../contracts/orders.schemas',
      },
      Order: {
        name: 'Order',
        runtimeSchema: dummySchema,
        modulePath: '/app/src/contracts/orders.schemas.ts',
        relativeModulePathFromGen: '../../../contracts/orders.schemas',
      },
    },
    operations: {
      createOrder: {
        name: 'createOrder',
        inputSchemaName: 'CreateOrder',
        outputSchemaName: 'Order',
        handler: {
          modulePath: '/app/src/handlers/order.handlers.ts',
          relativeModulePathFromGen: '../../../handlers/order.handlers',
          exportName: 'OrderHandlers',
          methodName: 'createOrder',
        },
        http: {
          method: 'POST',
          path: '/orders',
          successStatus: 201,
          summary: 'Create an order',
        },
        events: {
          inbound: {
            topic: 'orders.create.v1',
            event: 'order.create.requested.v1',
          },
          outbound: {
            topic: 'orders.created.v1',
            event: 'order.created.v1',
          },
        },
        rpc: {
          package: 'orders.v1',
          service: 'OrdersService',
          method: 'CreateOrder',
          inputFields: {
            customerId: { number: 1, type: 'string' },
            amount: { number: 2, type: 'double' },
            isPriority: { number: 3, type: 'bool' },
          },
          outputFields: {
            id: { number: 1, type: 'string' },
          },
        },
        authorization: {
          resource: 'order',
          action: 'create',
          policyModulePath: '/app/src/policies/order.policy.ts',
          relativePolicyModulePathFromGen: '../../../policies/order.policy',
        },
        tool: {
          name: 'create_order',
          description: 'Create an order for the authenticated principal',
        },
      },
      getOrder: {
        name: 'getOrder',
        inputSchemaName: 'CreateOrder',
        outputSchemaName: 'Order',
        handler: {
          modulePath: '/app/src/handlers/query.handlers.ts',
          relativeModulePathFromGen: '../../../handlers/query.handlers',
          exportName: 'QueryHandlers',
          methodName: 'getOrder',
        },
        http: {
          method: 'GET',
          path: '/orders/:id',
          successStatus: 200,
        },
        rpc: {
          package: 'orders.v1',
          service: 'OrdersService',
          method: 'GetOrder',
          inputFields: {
            id: { number: 1, type: 'string' },
          },
          outputFields: {
            id: { number: 1, type: 'string' },
          },
        },
        tool: {
          name: 'get_order',
          description: 'Get an order by ID',
        },
      },
    },
  };

  it('emitValidationSurface generates contracts.ts with validate functions', () => {
    const code = emitValidationSurface(sampleNormManifest);
    expect(code).toContain('// @generated by @di-framework/codegen — do not edit.');
    expect(code).toContain(
      "import type { CreateOrder, Order } from '../../../contracts/orders.schemas';",
    );
    expect(code).toContain('export function validateCreateOrder(input: unknown): CreateOrder');
    expect(code).toContain('export function validateOrder(input: unknown): Order');
  });

  it('emitHttpSurface generates @HttpRouter controller with POST and GET methods', () => {
    const code = emitHttpSurface(sampleNormManifest);
    expect(code).not.toBeNull();
    expect(code!).toContain('@HttpRouter(');
    expect(code!).toContain('export class OrdersV1HttpController');
    expect(code!).toContain('.post(');
    expect(code!).toContain('.get(');
  });

  it('emitEventsSurface generates @EventBridge with @Inbound and @Outbound', () => {
    const code = emitEventsSurface(sampleNormManifest);
    expect(code).not.toBeNull();
    expect(code!).toContain('@EventBridge()');
    expect(code!).toContain('export class OrdersV1Events');
    expect(code!).toContain("topic: 'orders.create.v1'");
    expect(code!).toContain("event: 'order.create.requested.v1'");
    expect(code!).toContain('validate: validateCreateOrder');
    expect(code!).toContain('outboundCreateOrder');
  });

  it('emitRpcSurface generates @RpcMessage and @RpcService with boolean types and multiple handlers', () => {
    const code = emitRpcSurface(sampleNormManifest);
    expect(code).not.toBeNull();
    expect(code!).toContain('@RpcMessage()');
    expect(code!).toContain('export class CreateOrderRequest');
    expect(code!).toContain("@RpcField({ number: 2, type: 'double' })");
    expect(code!).toContain('isPriority!: boolean');
    expect(code!).toContain("@RpcService({ package: 'orders.v1' })");
    expect(code!).toContain('export class OrdersV1RpcService');
    expect(code!).toContain('private orderHandlers!: OrderHandlers;');
    expect(code!).toContain('private queryHandlers!: QueryHandlers;');
  });

  it('emitToolsSurface generates @ToolSet and @Tool class with multiple handlers', () => {
    const code = emitToolsSurface(sampleNormManifest);
    expect(code).not.toBeNull();
    expect(code!).toContain('@ToolSet(');
    expect(code!).toContain('export class OrdersV1Tools');
    expect(code!).toContain("name: 'create_order'");
    expect(code!).toContain('inputSchema: CreateOrder.jsonSchema');
    expect(code!).toContain("action: 'create'");
    expect(code!).toContain('private orderHandlers!: OrderHandlers;');
    expect(code!).toContain('private queryHandlers!: QueryHandlers;');
  });

  it('returns null when surfaces are absent', () => {
    const emptyManifest: NormalizedManifest = {
      name: 'empty',
      version: 'v1',
      manifestFilePath: '/app/empty.ts',
      outputDir: '/app/out',
      managedByDi: true,
      schemas: {},
      operations: {},
    };

    expect(emitHttpSurface(emptyManifest)).toBeNull();
    expect(emitEventsSurface(emptyManifest)).toBeNull();
    expect(emitRpcSurface(emptyManifest)).toBeNull();
    expect(emitToolsSurface(emptyManifest)).toBeNull();
  });
});
